// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQh993W5oAnn3IhX19TIWqc-xZM8Qcqj4',
    appId: '1:9542573207:web:57014a9c29b970a428ddd2',
    messagingSenderId: '9542573207',
    projectId: 'fir-d11c9',
    authDomain: 'fir-d11c9.firebaseapp.com',
    storageBucket: 'fir-d11c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1pLHCRvE7Bawy_48d1_t_wFeQj6Lv-tE',
    appId: '1:9542573207:android:5daf62b4648fe91b28ddd2',
    messagingSenderId: '9542573207',
    projectId: 'fir-d11c9',
    storageBucket: 'fir-d11c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBABGgadbuEL9e_BcIY-ZKOy69mZ7xemhg',
    appId: '1:9542573207:ios:867d0342f33f8a4528ddd2',
    messagingSenderId: '9542573207',
    projectId: 'fir-d11c9',
    storageBucket: 'fir-d11c9.appspot.com',
    iosBundleId: 'com.example.projectcloth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBABGgadbuEL9e_BcIY-ZKOy69mZ7xemhg',
    appId: '1:9542573207:ios:867d0342f33f8a4528ddd2',
    messagingSenderId: '9542573207',
    projectId: 'fir-d11c9',
    storageBucket: 'fir-d11c9.appspot.com',
    iosBundleId: 'com.example.projectcloth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQh993W5oAnn3IhX19TIWqc-xZM8Qcqj4',
    appId: '1:9542573207:web:f548748fc97357ae28ddd2',
    messagingSenderId: '9542573207',
    projectId: 'fir-d11c9',
    authDomain: 'fir-d11c9.firebaseapp.com',
    storageBucket: 'fir-d11c9.appspot.com',
  );
}
